openapi: 3.0.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASAText
  description: una piattaforma di messaggistica che supporta chat individuali e di gruppo, accessibile tramite PC
  version: 1.0.0

paths:
  # SEZIONE 1 - Gli Utenti
  /users:
    # Creazione e autenticazione utente
    post:
      tags:
        - login
      summary: Login utente
      description: |-
        Se l'utente non esiste, verrà creato,
        e viene restituito un identificatore.
        Se l'utente esiste, viene restituito l'identificatore dell'utente.
      operationId: doLogin
      requestBody:
        description: dettagli utente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User' 
              required:
                - name
      responses:
        '201':
          description: Login utente riuscito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    # Ottenimento di tutti gli utenti
    get:
      tags:
        - login
      summary: Ottieni tutti gli utenti
      description: Restituisce la lista di tutti gli utenti registrati.
      operationId: getAllUsers
      responses:
        '200':
          description: Elenco utenti recuperato con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  # SEZIONE 1.1 - Utente specifico
  /users/{user_id}:
    get:
      tags:
        - login
      summary: Ottieni i dettagli di un utente specifico
      description: Restituisce i dettagli dell'utente identificato da user_id.
      operationId: getUserById
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: ID dell'utente da recuperare
      responses:
        '200':
          description: Dettagli utente recuperati con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Utente non trovato

  # SEZIONE 1.2 - Impostazioni nome utente
  /users/me:
    put:
      tags:
        - login
      summary: Imposta o aggiorna il nome utente
      description: |-
        Permette all'utente autenticato di impostare o modificare il proprio nome.
        Restituisce l'oggetto utente aggiornato.
      operationId: setMyUserName
      requestBody:
        description: Nuovo nome utente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Nome utente aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  # SEZIONE 2 - Le Conversazioni (Chat)
  /chats:

  # Ottengo tutte le chat dell'utente autenticato
    get:
      tags:
        - chats
      summary: Ottieni tutte le chat dell'utente autenticato
      description: Restituisce la lista di tutte le chat (individuali e di gruppo) dell'utente autenticato.
      operationId: getMyConversations
      responses:
        '200':
          description: Elenco chat recuperato con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chat'

    # Creazione di una nuova chat individuale o di gruppo
    post:
      tags:
        - chats
      summary: Crea una nuova chat
      description: |-
        Permette di creare una nuova chat individuale o di gruppo.
        Restituisce l'oggetto chat creato.
      operationId: createConversation
      requestBody:
        description: Dettagli della nuova chat
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        '201':
          description: Chat creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'

  # SEZIONE 2.1 - Chat specifica
  /chats/{chat_id}:
    get:
      tags:
        - chats
      summary: Ottieni i dettagli di una chat specifica
      description: Restituisce i dettagli della chat identificata da chat_id.
      operationId: getConversation
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
          description: ID della chat da recuperare
      responses:
        '200':
          description: Dettagli chat recuperati con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '404':
          description: Chat non trovata


components:
  schemas:

    # Schema per l'utente
    User:
      type: object
      properties:
        id:
          type: string
          example: "abcdef012345"
        name:
          type: string
          example: "Maria"
          minimum: 3
          maximum: 16

    # Schemi per la chat
    # Inizio creando uno schema che funge da superclasse con proprietà comuni a tutte le chat

    ChatBase:
      type: object 
      properties: 
        id: 
          type: string
          example: "chat123456"
        type:
          description: Tipo di chat (individuale con un altro utente o di gruppo)
          type: string
          enum:
            - individual
            - group
        participants:
          type: array
          items:
            type: string
          description: Elenco degli ID degli utenti partecipanti alla chat
        created_at:
          type: string
          format: date-time
          description: Data e ora di creazione della chat
          example: "2025-10-30T14:48:00.000Z"
        updated_at:
          type: string
          format: date-time
          description: Data e ora dell'ultimo aggiornamento della chat
          example: "2025-10-30T15:00:00.000Z"
        last_message:
          type: string
          format: date-time
          description: Data e ora dell'ultimo messaggio inviato nella chat
          example: "2025-10-30T15:00:00.000Z"
          
    # Passo alla prima sottoclasse: Chat individuale
    IndividualChat:
      allOf:
        - $ref: '#/components/schemas/ChatBase'
        - type: object
          properties:
            type:
              type: string
              enum:
                - individual
    
    # Seconda sottoclasse: Chat di gruppo
    GroupChat:
      allOf:
        - $ref: '#/components/schemas/ChatBase'
        - type: object
          properties:
            type:
              type: string
              enum:
                - group
            group_name:
              type: string
              description: Nome della chat di gruppo
              example: "Amici di Università"
            description:
              type: string
              description: Descrizione della chat di gruppo
              example: "Chat per organizzare gli eventi universitari"
            admins:
              type: array
              items:
                type: string
                description: Elenco degli ID degli utenti amministratori della chat di gruppo
            group_icon:
              type: string
              format: uri
              description: URL dell'icona della chat di gruppo
              example: "http://example.com/icons/group123.png"

    # Infine lo schema generico: una chat può essere individuale o di gruppo
    Chat:
      oneOf:
        - $ref: '#/components/schemas/IndividualChat'
        - $ref: '#/components/schemas/GroupChat'
      discriminator:
        propertyName: type
        mapping:
          individual: '#/components/schemas/IndividualChat'
          group: '#/components/schemas/GroupChat'
      description: Rappresenta una chat, che può essere individuale o di gruppo e questo schema verrà usato nelle risposte API.

   
      


    

    

  



